


// whatsapp
const DELIVERY_STATUS_ENUMS = ["NOT_AVAILABLE", "ACCEPTED", "SCHEDULED", "CANCELED", "QUEUED", "SENDING", "SENT", "FAILED", "DELIVERED", "UNDELIVERED", "RECEIVING", "READ"];

export default {
    DELIVERY_STATUS_ENUMS
}