import { ASSIGNEE_METHOD_ENUMS, SKILL_LEVELS, SKILL_TYPES, CREATE_WORKFLOW_AVAILABLE_ACTIONS, TASK_COMPLETION_ENUMS,
  ESCALATION_UNITS_ENUMS
 } from "./taskManagementConst";

import {
  COMMUNICATION_COMPONENT_SERVICE_TYPE,
  COMMUNICATION_COMPONENT_TYPES,
  TRIGGER_COMPONENT_TYPES,
} from "./triggerConst";

const EVENT_TYPES = {
  formula: "formula",
  trigger: "trigger",
};

const OBSOLETE_CONDITIONS = {
  observation: "observation",
  resolution: "resolution",
};

export default {
  SKILL_LEVELS,
  SKILL_TYPES,
  CREATE_WORKFLOW_AVAILABLE_ACTIONS,
  TASK_COMPLETION_ENUMS,
  ESCALATION_UNITS_ENUMS,
  EVENT_TYPES,
  TRIGGER_COMPONENT_TYPES,
  COMMUNICATION_COMPONENT_TYPES,
  COMMUNICATION_COMPONENT_SERVICE_TYPE,
  ASSIGNEE_METHOD_ENUMS,
  OBSOLETE_CONDITIONS,
};
