export const SENSOR_PURPOSE_TAGS: {
  key: string;
  abbr: string;
  name: string;
  isDeprecated: boolean;
}[] = [
  {
    key: "ph",
    abbr: "PH",
    name: "pH",
    isDeprecated: false,
  },
  {
    key: "bod",
    abbr: "BOD",
    name: "Biochemical Oxygen Demand",
    isDeprecated: false,
  },
  {
    key: "cod",
    abbr: "COD",
    name: "Chemical Oxygen Demand",
    isDeprecated: false,
  },
  {
    key: "turbidity",
    abbr: "TUR",
    name: "Turbidity",
    isDeprecated: false,
  },
  {
    key: "level",
    abbr: "LV",
    name: "Level",
    isDeprecated: false,
  },
  {
    key: "highLevelSwitch",
    abbr: "HLS",
    name: "High Level Switch",
    isDeprecated: false,
  },
  {
    key: "lowLevelSwitch",
    abbr: "LLS",
    name: "Low Level Switch",
    isDeprecated: false,
  },
  {
    key: "tds",
    abbr: "TDS",
    name: "Total Dissolved Solids",
    isDeprecated: false,
  },
  {
    key: "orp",
    abbr: "ORP",
    name: "Oxidation Reduction Potential",
    isDeprecated: false,
  },
  {
    key: "chlorine",
    abbr: "CA",
    name: "Chlorine",
    isDeprecated: false,
  },
  {
    key: "do",
    abbr: "DO",
    name: "Dissolved Oxygen",
    isDeprecated: false,
  },
  {
    key: "proximity",
    abbr: "PRX",
    name: "Proximity",
    isDeprecated: false,
  },
  {
    key: "pressure",
    abbr: "PR",
    name: "Pressure",
    isDeprecated: false,
  },
  {
    key: "flowSwitch",
    abbr: "FS",
    name: "Flow Switch",
    isDeprecated: false,
  },
  {
    key: "flowRate",
    abbr: "FR",
    name: "Flow Rate",
    isDeprecated: false,
  },
  {
    key: "flowTotalizer",
    abbr: "FT",
    name: "Flow Totalizer",
    isDeprecated: false,
  },
  {
    key: "energyUsedPerHour",
    abbr: "EUH",
    name: "Energy Used Per Hour",
    isDeprecated: false,
  },
  {
    key: "conductivity",
    abbr: "COND",
    name: "Conductivity",
    isDeprecated: false,
  },
  {
    key: "SDIAnalyser",
    abbr: "SDI",
    name: "SDI Analyser",
    isDeprecated: false,
  },
  {
    key: "TSS",
    abbr: "TSS",
    name: "Total Suspended Solids",
    isDeprecated: false,
  },
  {
    key: "Barscreenchoking",
    abbr: "BSC",
    name: "Bar Screen Choking",
    isDeprecated: false,
  },
  {
    key: "LoadCellWeight",
    abbr: "LCW",
    name: "Load Cell Weight",
    isDeprecated: false,
  },
  {
    key: "autoManual",
    abbr: "MAN",
    name: "Auto Manual",
    isDeprecated: false,
  },
  {
    key: "trip",
    abbr: "TRP",
    name: "Trip",
    isDeprecated: false,
  },
  {
    key: "onOff",
    abbr: "ONOFF",
    name: "ON/OFF",
    isDeprecated: false,
  },
  {
    key: "vibration",
    abbr: "VIB",
    name: "Vibration",
    isDeprecated: false,
  },
  {
    key: "frequency",
    abbr: "FRQV",
    name: "Frequency",
    isDeprecated: false,
  },
  {
    key: "current",
    abbr: "CURR",
    name: "Current",
    isDeprecated: false,
  },
  {
    key: "rpm",
    abbr: "RPM",
    name: "RPM",
    isDeprecated: false,
  },
  {
    key: "control",
    abbr: "CTRL",
    name: "Control",
    isDeprecated: false,
  },
  {
    key: "temperature",
    abbr: "TEMP",
    name: "Temperature",
    isDeprecated: false,
  },
  {
    key: "hmiBypass",
    abbr: "HMIB",
    name: "HMI Bypass",
    isDeprecated: false,
  },
  {
    key: "softwareBypass",
    abbr: "SFTB",
    name: "Software Bypass",
    isDeprecated: false,
  },
  {
    key: "bidirectional",
    abbr: "BINL",
    name: "Bidirectional",
    isDeprecated: false,
  },
  {
    key: "sv30",
    abbr: "SV30",
    name: "SV30",
    isDeprecated: false,
  },
  {
    key: "sv60",
    abbr: "SV60",
    name: "SV60",
    isDeprecated: false,
  },
  {
    key: "sv90",
    abbr: "SV90",
    name: "SV90",
    isDeprecated: false,
  },
  {
    key: "sv30Turbidity",
    abbr: "SV30TU",
    name: "SV30 Turbidity",
    isDeprecated: false,
  },
  {
    key: "flooding",
    abbr: "FLO",
    name: "Flooding Sensor",
    isDeprecated: false,
  },
  {
    key: "vfdOnOrOff",
    abbr: "VFDONOFF",
    name: "VFD ON/OFF",
    isDeprecated: false,
  },
  {
    key: "vfdRpm",
    abbr: "VFDRPM",
    name: "VFD RPM",
    isDeprecated: false,
  },
  {
    key: "vfdAmpere",
    abbr: "VFDAMP",
    name: "VFD Ampere",
    isDeprecated: false,
  },
  {
    key: "sv30Image",
    abbr: "SV30I",
    name: "SV30 Image",
    isDeprecated: false,
  },
  {
    key: "sv60Image",
    abbr: "SV60I",
    name: "SV60 Image",
    isDeprecated: false,
  },
  {
    key: "sv90Image",
    abbr: "SV90I",
    name: "SV90 Image",
    isDeprecated: false,
  },
  {
    key: "svCustomImage",
    abbr: "SVCI",
    name: "SV Custom Image",
    isDeprecated: false,
  },
  {
    key: "svRaw",
    abbr: "SVRAW",
    name: "SV Raw",
    isDeprecated: false,
  },
  {
    key: "svRawImage",
    abbr: "SVRI",
    name: "SV Raw Image",
    isDeprecated: false,
  },
  {
    key: "svFloatingSludge",
    abbr: "SVFS",
    name: "SV Floating Sludge",
    isDeprecated: false,
  },
  {
    key: "valveOpen",
    abbr: "VO",
    name: "Valve Open",
    isDeprecated: false,
  },
  {
    key: "valveClose",
    abbr: "VC",
    name: "Valve Close",
    isDeprecated: false,
  },
  {
    key: "valveOpened",
    abbr: "VOP",
    name: "Valve Opened",
    isDeprecated: false,
  },
  {
    key: "valveClosed",
    abbr: "VCL",
    name: "Valve Closed",
    isDeprecated: false,
  },
  {
    key: "valveAuto",
    abbr: "VA",
    name: "Valve Auto",
    isDeprecated: false,
  },
  {
    key: "barScreen25",
    abbr: "BS25",
    name: "Bar Screen 25%",
    isDeprecated: false,
  },
  {
    key: "barScreen50",
    abbr: "BS50",
    name: "Bar Screen 50%",
    isDeprecated: false,
  },
  {
    key: "barScreen75",
    abbr: "BS75",
    name: "Bar Screen 75%",
    isDeprecated: false,
  },
  {
    key: "barScreen100",
    abbr: "BS100",
    name: "Bar Screen 100%",
    isDeprecated: false,
  },
  {
    key: "voltage",
    abbr: "VOLT",
    name: "Voltage",
    isDeprecated: false,
  },
  {
    key: "power",
    abbr: "POWE",
    name: "Power",
    isDeprecated: false,
  },
  {
    key: "mlss",
    abbr: "MLSS",
    name: "Mixed Liquor Suspended Solid",
    isDeprecated: false,
  },
  {
    key: "frwd",
    abbr: "FRWD",
    name: "Forward",
    isDeprecated: false,
  },
  {
    key: "frwdLimit",
    abbr: "FRWDLT",
    name: "Forward Limit",
    isDeprecated: false,
  },
  {
    key: "rvrse",
    abbr: "RVRSE",
    name: "Reverse",
    isDeprecated: false,
  },
  {
    key: "rvrseLimit",
    abbr: "RVRSELT",
    name: "Reverse Limit",
    isDeprecated: false,
  },
  {
    key: "hooter",
    abbr: "HTR",
    name: "Hooter",
    isDeprecated: false,
  },
  {
    key: "sdiAnalyzer",
    abbr: "SDAN",
    name: "SDI Analyzer",
    isDeprecated: false,
  },
  {
    key: "decanterAuto",
    abbr: "DEAU",
    name: "Decanter Auto",
    isDeprecated: false,
  },
  {
    key: "decanterUp",
    abbr: "DEUP",
    name: "Decanter Up",
    isDeprecated: false,
  },
  {
    key: "decanterDown",
    abbr: "DEDN",
    name: "Decanter Down",
    isDeprecated: false,
  },
  {
    key: "decanterPnpUp",
    abbr: "DCPNPUP",
    name: "Decanter PNP Up",
    isDeprecated: false,
  },
  {
    key: "decanterPnpDown",
    abbr: "DCPNDN",
    name: "Decanter PNP Down",
    isDeprecated: false,
  },
  {
    key: "decanterTrip",
    abbr: "DCTP",
    name: "Decanter Trip",
    isDeprecated: false,
  },
  {
    key: "rPhaseCurrent ",
    abbr: "RCURR",
    name: "R Phase Current",
    isDeprecated: false,
  },
  {
    key: "yPhaseCurrent",
    abbr: "YCURR",
    name: "Y Phase Current",
    isDeprecated: false,
  },
  {
    key: "bPhaseCurrent",
    abbr: "BCURR",
    name: "B Phase Current",
    isDeprecated: false,
  },
  {
    key: "averageCurrent",
    abbr: "AVGCURR",
    name: "Average Current",
    isDeprecated: false,
  },
  {
    key: "levelTransmitter",
    abbr: "LT",
    name: "Level Transmitter",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitter",
    abbr: "PT",
    name: "Pressure Transmitter",
    isDeprecated: true,
  },
  {
    key: "sv30Sensor",
    abbr: "SV",
    name: "SV30 Sensor",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitterInlet",
    abbr: "PTI",
    name: "Pressure Transmitter Inlet",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitterOutlet",
    abbr: "PTO",
    name: "Pressure Transmitter Outlet",
    isDeprecated: true,
  },
  {
    key: "pressureSwitchInlet",
    abbr: "PSI",
    name: "Pressure Switch Inlet",
    isDeprecated: true,
  },
  {
    key: "pressureSwitchOutlet",
    abbr: "PSO",
    name: "Pressure Switch Outlet",
    isDeprecated: true,
  },
  {
    key: "conductivityMeter",
    abbr: "CM",
    name: "Conductivity Meter",
    isDeprecated: true,
  },
  {
    key: "conductivityMeterSwitch",
    abbr: "CMS",
    name: "Conductivity Meter Switch",
    isDeprecated: true,
  },
  {
    key: "proximitySensor",
    abbr: "PS",
    name: "Proximity Sensor",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitterBackwash",
    abbr: "PTBWS",
    name: "Pressure Transmitter Backwash",
    isDeprecated: true,
  },
  {
    key: "micronCartridgeInletPressure",
    abbr: "CATPT",
    name: "Micron cartridge inlet pressure",
    isDeprecated: true,
  },
  {
    key: "flowSwitchInBackwashLine",
    abbr: "BWS",
    name: "Flow switch in backwash line",
    isDeprecated: true,
  },
  {
    key: "inletTurbidity",
    abbr: "TURI",
    name: "Inlet Turbidity",
    isDeprecated: true,
  },
  {
    key: "inletChlorine",
    abbr: "CHLI",
    name: "Inlet Chlorine",
    isDeprecated: true,
  },
  {
    key: "inletTds",
    abbr: "TDSI",
    name: "Inlet TDS",
    isDeprecated: true,
  },
  {
    key: "inletPh",
    abbr: "PHI",
    name: "Inlet PH",
    isDeprecated: true,
  },
  {
    key: "bagFilterPressureTransmitter",
    abbr: "BAGFILPT",
    name: "Bag Filter Pressure Transmitter",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitterReject",
    abbr: "PTREJ",
    name: "Pressure Transmitter Reject",
    isDeprecated: true,
  },
  {
    key: "pressureTransmitterPermeate",
    abbr: "PTPERM",
    name: "Pressure Transmitter Permeate",
    isDeprecated: true,
  },
  {
    key: "ampereSensor",
    abbr: "AMP",
    name: "Ampere Sensor",
    isDeprecated: true,
  },
  {
    key: "barScreenPercentageSensor",
    abbr: "PER",
    name: "Bar Screen Percentage Sensor",
    isDeprecated: true,
  },
  {
    key: "temperatureSensor",
    abbr: "TMP",
    name: "Temperature Sensor",
    isDeprecated: true,
  },
  {
    key: "vfdAmpereSensor",
    abbr: "AMPV",
    name: "VFD Ampere Sensor",
    isDeprecated: true,
  },
  {
    key: "vfdRpmSensor",
    abbr: "RPMV",
    name: "VFD RPM Sensor",
    isDeprecated: true,
  },
  {
    key: "airFlowmeter",
    abbr: "AIRFMF",
    name: "Air Flowmeter",
    isDeprecated: true,
  },
  {
    key: "vibrationSensor",
    abbr: "VBS",
    name: "Vibration Sensor",
    isDeprecated: true,
  },
  {
    key: "flowStatus",
    abbr: "FMF",
    name: "Flow Status",
    isDeprecated: true,
  },
  {
    key: "flowmeter",
    abbr: "FLW",
    name: "Flowmeter",
    isDeprecated: true,
  },
];

export const sensorInputType = ["Modbus", "Analog", "Digital"];
