export const sensorPurposeTags = [
  "ph",
  "bod",
  "cod",
  "turbidity",
  "level",
  "highLevelSwitch",
  "lowLevelSwitch",
  "tds",
  "orp",
  "chlorine",
  "do",
  "proximity",
  "pressure",
  "flowSwitch",
  "flowRate",
  "flowTotalizer",
  "energyUsedPerHour",
  "totalEnergyUsed",
  "conductivity",
  "sdianalyser",
  "tss",
  "barscreenchoking",
  "LoadCellWeight",
  "autoManual",
  "trip",
  "onOff",
  "vibration",
  "frequency",
  "current",
  "rpm",
];

export const sensorInputType = ["Modbus", "Analog", "Digital"];
